CloudberryGrocer/urls.py
from django.contrib import admin
from django.urls import path, include
import products.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', products.views.IndexView.as_view(), name='home_page_route'),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include("checkout.urls")),
    path('mykitchen/', include('mykitchen.urls'))
]

cart/urls.py
from django.urls import path
import cart.views

urlpatterns = [
    path('view', cart.views.view_cart,
         name="view_cart"),
    path('add/<product_id>', cart.views.add_to_cart,
         name="add_to_cart"),
    path('subtract/<product_id>', cart.views.subtract_from_cart,
         name="subtract_from_cart"),
    path('update/<product_id>', cart.views.manual_update_qty,
         name="update_cart_qty"),
    path('remove/<product_id>', cart.views.remove_item_from_cart,
         name="remove_from_cart")
]

products/urls.py
from django.urls import path
import products.views


urlpatterns = [
    path('', products.views.IndexView.as_view(),
         name="home_page_route"),
    path('directory', products.views.DirectoryView.as_view(),
         name="product_directory_route"),
    path('create', products.views.CreateProduct.as_view(),
         name="create_product_route"),
    path('update/<int:pk>', products.views.UpdateProduct.as_view(),
         name="update_product_route"),
    path('delete/<int:pk>', products.views.DeleteProduct.as_view(),
         name="delete_product_route"),
    path('details/<int:pk>', products.views.ProductDetailView.as_view(),
         name="product_detail_route"),
    path('breakfast', products.views.CategoryView.as_view(),
         name="category_product_route"),
    path('biscuits-and-cookies', products.views.CategoryView.as_view(),
         name="category_product_route"),
    path('grains-and-dried-beans', products.views.CategoryView.as_view(),
         name="category_product_route"),
    path('nuts', products.views.CategoryView.as_view(),
         name="category_product_route"),
    path('baking-ingredients', products.views.CategoryView.as_view(),
         name="category_product_route"),
    path('fresh-produce', products.views.CategoryView.as_view(),
         name="category_product_route"),
    path('brands', products.views.BrandListView.as_view(),
         name="view_brand_route"),
    path('create-brands', products.views.BrandAdd.as_view(),
         name="create_brand_route"),
    path('update-brands/<int:pk>', products.views.BrandUpdate.as_view(),
         name="update_brand_route"),
    path('delete-brands/<int:pk>', products.views.BrandDelete.as_view(),
         name="delete_brand_route"),
    path('subcategory', products.views.SubcategoryListView.as_view(),
         name="view_subcategory_route"),
    path('add-subcategory', products.views.AddSubcategory.as_view(),
         name="add_subcategory_route"),
    path('update-subcategory/<int:pk>',
         products.views.UpdateSubcategory.as_view(),
         name="update_subcategory_route"),
    path('delete-subcategory/<int:pk>',
         products.views.DeleteSubcategory.as_view(),
         name="delete_subcategory_route"),
    path('usage', products.views.UsageListView.as_view(),
         name="view_usage_route"),
    path('add-usage', products.views.AddUsage.as_view(),
         name="add_usage_route"),
    path('update-usage/<int:pk>',
         products.views.UpdateUsage.as_view(),
         name="update_usage_route"),
    path('delete-usage/<int:pk>',
         products.views.DeleteUsage.as_view(),
         name="delete_usage_route")
]

products/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Brand(models.Model):
    name = models.CharField(blank=False, max_length=50)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(blank=False, max_length=50)

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    name = models.CharField(blank=False, max_length=50)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(blank=False, max_length=50)
    cat_no = models.IntegerField(blank=False)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.name


class Usage(models.Model):
    name = models.CharField(blank=False, max_length=50)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(blank=False, max_length=50)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE)
    desc = models.TextField(blank=False, max_length=500)
    origin = models.ForeignKey('Country', on_delete=models.CASCADE)
    weight_per_pack = models.FloatField(blank=False)
    qty_per_pack = models.IntegerField(blank=True, null=True)
    barcode_spec = models.CharField(blank=True, max_length=3)
    barcode_no = models.BigIntegerField(blank=True, null=True)
    image = models.URLField(blank=False)
    root_price = models.DecimalField(max_digits=10, decimal_places=3,
                                     blank=False)
    multiplier = models.DecimalField(max_digits=5, decimal_places=3,
                                     blank=False, default=1.00)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    subcategory = models.ManyToManyField(Subcategory)
    usage = models.ManyToManyField('Usage')
    editor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_edited = models.DateTimeField(auto_now_add=True, blank=True)

    SALE_STATUS = (
        ('b', 'Best Sellers'),
        ('d', 'Bulk Discount'),
        ('n', 'Normal'),
        ('o', 'On Offer')
    )

    status = models.CharField(
        max_length=1,
        choices=SALE_STATUS,
        blank=True,
        default='n',
        help_text='Product Sale Status',
    )

    def __str__(self):
        return self.name

    def get_current_price(self):
        return self.root_price * self.multiplier

products/forms.py
from django import forms
from .models import Product

from crispy_forms.helper import FormHelper
from crispy_forms import layout
from crispy_forms.layout import Submit
from crispy_forms.bootstrap import Div


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name', 'brand', 'desc', 'origin', 'weight_per_pack',
                  'qty_per_pack', 'barcode_spec', 'barcode_no', 'image',
                  'root_price', 'multiplier', 'category', 'subcategory',
                  'usage', 'status')
        widgets = {
            'editor': forms.HiddenInput(),
            'date_edited': forms.HiddenInput()
        }


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False,
                             help_text = "e.g rice")
    min_price = forms.DecimalField(
        max_digits=10, decimal_places=2, required=False, help_text="e.g. 0.30")
    max_price = forms.DecimalField(
        max_digits=10, decimal_places=2, required=False, help_text="e.g. 9.99")

    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.method = "GET"
        self.helper.layout = layout.Layout(
            Div(
                Div('search', css_class="col-md-3"),
                Div('min_price', css_class="col-md-3"),
                Div('max_price', css_class="col-md-3"),
                Submit('submit', 'Search',
                       css_class="btn-success align-self-center ml-5"),
                css_class="row",
            )
        )

products/views.py
from django.shortcuts import (render, reverse,
                              redirect, get_object_or_404)
from django.contrib import messages
from .models import Product, Category, Brand, Subcategory, Usage
from .forms import ProductForm, SearchForm
from django.db.models import Q
import datetime
import re
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy


# Create your views here.


class IndexView(TemplateView):
    """Home Page View"""
    template_name = "products/index.template.html"
    model = Category

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all products on offer
        context['categories'] = Category.objects.all()
        context['products_on_offer'] = Product.objects.filter(
            status__exact='o')
        return context


class DirectoryView(ListView):
    """Directory Page View"""
    model = Product
    search_input = ""
    form_class = SearchForm
    template_name = "products/directory.template.html"

    def get_queryset(self):
        # default : find all products
        return self.model.objects.all()

    def get(self, request, *args, **kwargs):
        self.search_form = self.form_class(self.request.GET)

        # always true query:
        queries = ~Q(pk__in=[])
        # if a name is specified, add it to the query
        if ('search' in self.request.GET and self.request.GET['search']):
            self.search_input = self.request.GET['search']
            queries = queries & Q(name__icontains=self.search_input)

        # if a min_price is specified, add it to query
        if 'min_price' in self.request.GET and self.request.GET['min_price']:
            min_price = float(self.request.GET['min_price'])
        else:
            min_price = 0.00

        # if a max_price is specified, add it to query
        if 'max_price' in self.request.GET and self.request.GET['max_price']:
            max_price = float(self.request.GET['max_price'])
        else:
            max_price = 99999.99

        queries = queries & Q(root_price__gte=min_price) & Q(
            root_price__lte=max_price)

        self.object_list = self.model.objects.filter(queries)

        context = self.get_context_data(products=self.object_list,
                                        search_form=self.search_form,
                                        search_input=self.search_input)

        return self.render_to_response(context)


class CategoryView(ListView):
    """ View Products By Category """
    model = Product
    template_name = 'products/bycategory.template.html'

    def get_queryset(self):
        path = self.request.get_full_path()
        result = re.search(r"(?!.*/).+", path).group(0)
        result_list = result.split("-")
        regex_str = result_list[0]
        self.page_title = " ".join(result_list)
        return self.model.objects.filter(
            category__name__icontains=regex_str).order_by('name')

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        context = self.get_context_data(searched_products=self.object_list,
                                        page_title=self.page_title
                                        )
        return self.render_to_response(context)


class ProductDetailView(DetailView):
    """ View Product Details """
    model = Product
    template_name = 'products/details.template.html'


class BrandListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    """ View All Brands (Staff Access) """
    permission_required = ('products.view_brand')
    model = Brand
    template_name = 'products/brands.template.html'
    ordering = ['name']


class BrandAdd(LoginRequiredMixin, PermissionRequiredMixin,
               SuccessMessageMixin, CreateView):
    """ Input Brands (Staff Access) """
    permission_required = ('products.add_brand')
    model = Brand
    fields = ['name']
    template_name_suffix = '_create_form'
    success_url = reverse_lazy('home_page_route')
    success_message = "Brand %(name)s was created successfully"


class BrandUpdate(LoginRequiredMixin, PermissionRequiredMixin,
                  SuccessMessageMixin, UpdateView):
    """ Update Brands (Staff Access) """
    permission_required = ('products.change_brand')
    model = Brand
    fields = ['name']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('home_page_route')
    success_message = "Brand %(name)s was updated successfully"


class BrandDelete(LoginRequiredMixin, PermissionRequiredMixin,
                  SuccessMessageMixin, DeleteView):
    """ Delete Brands (Staff Access) """
    permission_required = ('products.delete_brand')
    model = Brand
    fields = ['name']
    success_url = reverse_lazy('home_page_route')
    success_message = "Brand %(name)s was deleted successfully"

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super(BrandDelete, self).delete(request, *args, **kwargs)


class SubcategoryListView(LoginRequiredMixin, PermissionRequiredMixin,
                          ListView):
    """ View All SubCategory (Staff Access) """
    permission_required = ('products.view_subcategory')
    model = Subcategory
    template_name = 'products/subcategory.template.html'
    ordering = ['name']


class AddSubcategory(LoginRequiredMixin, PermissionRequiredMixin,
                     SuccessMessageMixin, CreateView):
    """ Add Subcategory (Staff Access) """
    permission_required = ('products.add_subcategory')
    model = Subcategory
    fields = ['name']
    template_name_suffix = '_add_form'
    success_url = reverse_lazy('home_page_route')
    success_message = (
        "Subcategory %(name)s was created successfully on %(date)s")

    def get_success_message(self, cleaned_data):
        return self.success_message % {
            'name': self.object.name,
            'date': datetime.datetime.now().strftime('%b %d, %Y, %H:%M:%S')
        }


class UpdateSubcategory(LoginRequiredMixin, PermissionRequiredMixin,
                        SuccessMessageMixin, UpdateView):
    """ Update Subcategory (Staff Access) """
    permission_required = ('products.change_subcategory')
    model = Subcategory
    fields = ['name']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('home_page_route')
    success_message = (
        "Subcategory %(name)s was updated successfully on %(date)s")

    def get_success_message(self, cleaned_data):
        return self.success_message % {
            'name': self.object.name,
            'date': datetime.datetime.now().strftime('%b %d, %Y, %H:%M:%S')
        }


class DeleteSubcategory(LoginRequiredMixin, PermissionRequiredMixin,
                        SuccessMessageMixin, DeleteView):
    """ Delete Subcategory (Staff Access) """
    permission_required = ('products.delete_subcategory')
    model = Subcategory
    fields = ['name']
    success_url = reverse_lazy('home_page_route')
    success_message = "Subcategory %(name)s was deleted successfully"

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super(DeleteSubcategory, self).delete(request, *args, **kwargs)


class UsageListView(LoginRequiredMixin, PermissionRequiredMixin,
                    ListView):
    """ View All Usage (Staff Access) """
    permission_required = ('products.view_usage')
    model = Usage
    template_name = 'products/usage.template.html'
    ordering = ['name']


class AddUsage(LoginRequiredMixin, PermissionRequiredMixin,
               SuccessMessageMixin, CreateView):
    """ Add Usage (Staff Access) """
    permission_required = ('products.add_usage')
    model = Usage
    fields = ['name']
    template_name_suffix = '_add_form'
    success_url = reverse_lazy('home_page_route')
    success_message = (
        "Usage %(name)s was created successfully on %(date)s")

    def get_success_message(self, cleaned_data):
        return self.success_message % {
            'name': self.object.name,
            'date': datetime.datetime.now().strftime('%b %d, %Y, %H:%M:%S')
        }


class UpdateUsage(LoginRequiredMixin, PermissionRequiredMixin,
                  SuccessMessageMixin, UpdateView):
    """ Update Usage (Staff Access) """
    permission_required = ('products.change_usage')
    model = Usage
    fields = ['name']
    template_name_suffix = '_update_form'
    success_url = reverse_lazy('home_page_route')
    success_message = (
        "Usage %(name)s was updated successfully on %(date)s")

    def get_success_message(self, cleaned_data):
        return self.success_message % {
            'name': self.object.name,
            'date': datetime.datetime.now().strftime('%b %d, %Y, %H:%M:%S')
        }


class DeleteUsage(LoginRequiredMixin, PermissionRequiredMixin,
                  SuccessMessageMixin, DeleteView):
    """ Delete Usage (Staff Access) """
    permission_required = ('products.delete_usage')
    model = Usage
    fields = ['name']
    success_url = reverse_lazy('home_page_route')
    success_message = "Usage %(name)s was deleted successfully"

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        messages.success(self.request, self.success_message % obj.__dict__)
        return super(DeleteUsage, self).delete(request, *args, **kwargs)


class CreateProduct(LoginRequiredMixin, PermissionRequiredMixin,

products/templates/products/brand_create_form.html
{% extends 'base.template.html' %}
{%load static%}

{%block title%} Create Brand Name Form {%endblock%}

{% block content %}
<h3> Input Brand Name </h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-general">
</form>
{% endblock %}

products/templates/products/brand_update_form.html
{% extends 'base.template.html' %}
{%load static%}

{%block title%} Edit Brand Name Form {%endblock%}

{% block content %}
<h3> Edit Brand Name </h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" class="btn btn-general">
</form>
{% endblock %}

products/templates/products/brands.template.html
{% extends 'base.template.html' %}
{%load static%}

{%block title%} All Brands of Product {%endblock%}

{%block content%}

{% if perms.products.add_brand %}
<a class="btn btn-secondary btn-lg floating-btn" href="{% url 'create_brand_route' %}" role="button"
	data-toggle="tooltip" data-placement="bottom" title="Add brand">+</a>
{% endif %}


{% if brand_list %}
<div class="list-group">
	{% for brand in brand_list%}
	<div class="list-group-item d-flex">
		<div class="col">
			{{brand.name}}
		</div>
		<div class="col">
			<a class="btn btn-primary" href="{% url 'update_brand_route' pk=brand.id%}"
				role="button"><i class="fas fa-pen-alt"></i>Edit</a>
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal-{{brand.id}}">
    <i class="fas fa-trash-alt"></i>Delete
    </button>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="deleteModal-{{brand.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
		aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="deleteModalLabel">Do you want to delete this Brand?</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                         <span aria-hidden="true">&times;</span>
                        </button>
				</div>
				<div class="modal-body">
					<p>Deleting a brand will remove it permanently. This action cannot be undone.</p>
				</div>
				<div class="modal-footer">
					<form action="{%url 'delete_brand_route' pk=brand.id%}" method="POST">
						{% csrf_token %}
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<input type="submit" class="btn btn-danger" value="CONFIRM"/>
        </form>
				</div>
			</div>
		</div>
	</div>

	{% endfor %}
</div>
{% endif %}
{%endblock%}

{%block js%}

{%endblock%}

products/templates/products/directory.template.html
{% extends 'base.template.html' %}
{%load static %}
{%load crispy_forms_tags %}

{%block title%}
Cloudberry Grocer Directory
{%endblock%}

{% block content%}

<form method="GET" class="form-inline my-2 my-lg-0">
	{%crispy search_form%}
</form>


<div class="mt-5 mb-3">
	<h5>Results for "{{search_input}}"</h5>
	*Please note that the search results for prices are returned based on the price prior to discount.
</div>


{% if perms.products.add_product %}
<a class="btn btn-secondary btn-lg floating-btn" href="{% url 'create_product_route' %}" role="button"
	data-toggle="tooltip" data-placement="bottom" title="Add products">+</a>
{% endif %}


<div class="row mb-3 row-cols-12">
	<div class="card-deck">
		<!--startdeck-->
		{%for product in products %}
		{% if forloop.counter0|divisibleby:5 and forloop.counter0 != 0 %}
	</div>
	<!--end deck-->
</div>
<!--end row-->
<div class="row mb-3 row-cols-12">
	<div class="card-deck mt-5 mb-2">
		<!--startdeck-->
		{% endif %}


		<div class="card col-md-2">
			<a href="{% url 'product_detail_route' pk=product.id %}">
				<img src="{{product.image}}" class="card-img-top rounded" alt="product-image">
                </a>
				<div class="card-body product-container">

					{%if product.multiplier != 1.0 %}
					<h5 class="card-title">${{product.get_current_price|floatformat:2}}</h5>
					<h5 class="card-title">
						<small class="text-muted original-price">${{product.root_price|floatformat:2}}</small></h5>
					{% else %}
					<h5 class="card-title">${{product.root_price|floatformat:2}}</h5>
					{% endif %}
					<p class="card-text">{{product.name}}</p>
					<div class="card-bottom">
						{%if product.weight_per_pack < 1000 %}
						<p class="card-text">{{product.weight_per_pack}}g</p>
						{%else%}
						<p class="card-text">{{product.weight_per_pack|stringformat:"e"|cut:"0000e+03"}}kg</p>
						{% endif %}
						<a href="{% url 'add_to_cart' product_id=product.id %}" class="link">
							<span class="d-inline-flex">
                         <img src="{% static '/image/shopping-cart.svg' %}"/>
							<p class="card-text"><small class="text-muted">Add to Cart</small></p>
                         </span>
						</a>
					</div>
					{% if perms.products.change_product %}
					<div class="card-footer">
						<a class="btn btn-primary" href="{% url 'update_product_route' pk=product.id%}"
							role="button">Edit</a>
						<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal-{{product.id}}">
                             Delete
                            </button>
					</div>
					{% endif%}
				</div>
		</div>

		<!-- Modal -->
		<div class="modal fade" id="deleteModal-{{product.id}}" tabindex="-1" role="dialog"
			aria-labelledby="deleteModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel">Do you want to delete this Product?</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
					</div>
					<div class="modal-body">
						<p>Deleting a product will remove it permanently. This action cannot be undone.</p>
					</div>
					<div class="modal-footer">
						<form action="{%url 'delete_product_route' pk=product.id%}" method="POST">
							{% csrf_token %}
							<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
							<input type="submit" class="btn btn-danger" value="CONFIRM"/>
        </form>
					</div>
				</div>
			</div>
		</div>
		{%endfor%}

	</div>
	<!--end deck last-->
</div>
<!--end row last-->

{%endblock%}

{%block js%}
<script src="{% static '/js/main.js' %}"></script>
{%endblock%}

products/templates/products/input_product.template.html
{% extends 'base.template.html' %}
{%load crispy_forms_tags %}
{%load static%}


{%block title%} Cloudberry Input Product {%endblock%}
{%block content%}
    <h1>New Products Form</h1>
    <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit"/>
    </form>    
  {% endblock %}

products/templates/products/product_create_form.html
{% extends 'base.template.html' %}
{%load crispy_forms_tags %}
{%load static%}


{%block title%} Cloudberry Input Product Form {%endblock%}
{%block content%}
<h1>New Products Form</h1>
<form method="POST">
	{% csrf_token %}
	{{ form|crispy }}
	<input type="submit" value="Submit" class="btn btn-general"/>
    </form>
	{% endblock %}

products/templates/products/product_update_form.html
{% extends 'base.template.html' %}
{%load crispy_forms_tags %}
{%load static%}

{%block title%} Cloudberry Update Product {%endblock%}
{%block content%}
<h1>Edit Products Form</h1>
<form method="POST">
	{% csrf_token %}
	{{ form|crispy}}
	<input type="submit" value="Submit" class="btn btn-general"/>
    </form>
	{% endblock %}

products/templates/products/subcategory.template.html
{% extends 'base.template.html' %}
{%load static%}

{%block title%} All Subcategory of Product {%endblock%}

{%block content%}

{% if perms.products.add_subcategory %}
<a class="btn btn-secondary btn-lg floating-btn" href="{% url 'add_subcategory_route' %}" role="button"
	data-toggle="tooltip" data-placement="bottom" title="Add subcategory">+</a>
{% endif %}


{% if subcategory_list %}
<div class="list-group">
	{% for subcategory in subcategory_list%}
	<div class="list-group-item d-flex">
		<div class="col">
			{{subcategory.name}}
		</div>
		<div class="col">
			<a class="btn btn-primary" href="{% url 'update_subcategory_route' pk=subcategory.id%}"
				role="button"><i class="fas fa-pen-alt"></i>Edit</a>
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal-{{subcategory.id}}">
    <i class="fas fa-trash-alt"></i>Delete
    </button>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="deleteModal-{{subcategory.id}}" tabindex="-1" role="dialog"
		aria-labelledby="deleteModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="deleteModalLabel">Do you want to delete this sub-Category?</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                         <span aria-hidden="true">&times;</span>
                        </button>
				</div>
				<div class="modal-body">
					<p>Deleting a sub-category will remove it permanently. This action cannot be undone.</p>
				</div>
				<div class="modal-footer">
					<form action="{%url 'delete_subcategory_route' pk=subcategory.id%}" method="POST">
						{% csrf_token %}
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<input type="submit" class="btn btn-danger" value="CONFIRM"/>
        </form>
				</div>
			</div>
		</div>
	</div>

	{% endfor %}
</div>
{% endif %}
{%endblock%}

products/templates/products/usage.template.html
{% extends 'base.template.html' %}
{%load static%}

{%block title%} List of Product Usage {%endblock%}

{%block content%}

{% if perms.products.add_usage %}
<a class="btn btn-secondary btn-lg floating-btn" href="{% url 'add_usage_route' %}" role="button" data-toggle="tooltip"
	data-placement="bottom" title="Add Usage">+</a>
{% endif %}


{% if usage_list %}
<div class="list-group">
	{% for usage in usage_list%}
	<div class="list-group-item d-flex">
		<div class="col">
			{{usage.name}}
		</div>
		<div class="col">
			<a class="btn btn-primary" href="{% url 'update_usage_route' pk=usage.id%}"
				role="button"><i class="fas fa-pen-alt"></i>Edit</a>
			<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal-{{usage.id}}">
    <i class="fas fa-trash-alt"></i>Delete
    </button>
		</div>
	</div>

	<!-- Modal -->
	<div class="modal fade" id="deleteModal-{{usage.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
		aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="deleteModalLabel">Do you want to delete this product usage information?
					</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                         <span aria-hidden="true">&times;</span>
                        </button>
				</div>
				<div class="modal-body">
					<p>Deleting a product usage information will remove it permanently. This action cannot be undone.
					</p>
				</div>
				<div class="modal-footer">
					<form action="{%url 'delete_usage_route' pk=usage.id%}" method="POST">
						{% csrf_token %}
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<input type="submit" class="btn btn-danger" value="CONFIRM"/>
        </form>
				</div>
			</div>
		</div>
	</div>

	{% endfor %}
</div>
{% endif %}
{%endblock%}