CloudberryGrocer/urls.py
from django.contrib import admin
from django.urls import path, include
import products.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', products.views.IndexView.as_view(), name='home_page_route'),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include("checkout.urls")),
    path('mykitchen/', include('mykitchen.urls'))
]

cart/urls.py
from django.urls import path
import cart.views

urlpatterns = [
    path('view', cart.views.view_cart,
         name="view_cart"),
    path('add/<product_id>', cart.views.add_to_cart,
         name="add_to_cart"),
    path('subtract/<product_id>', cart.views.subtract_from_cart,
         name="subtract_from_cart"),
    path('update/<product_id>', cart.views.manual_update_qty,
         name="update_cart_qty"),
    path('remove/<product_id>', cart.views.remove_item_from_cart,
         name="remove_from_cart")
]

mykitchen/urls.py
from django.urls import path
import mykitchen.views

urlpatterns = [
    path('', mykitchen.views.index,
         name="mykitchen_home_page"),
    path('register', mykitchen.views.register_household,
         name="register_household"),
    path('view-household/<int:household_id>', mykitchen.views.view_household,
         name="view_household"),
    path('edit-household/<int:household_id>', mykitchen.views.edit_household,
         name="edit_household"),
    path('delete-household/<int:household_id>',
         mykitchen.views.delete_household,
         name="delete_household"),
    path('all-storage/<int:household_id>',
         mykitchen.views.view_storage_location,
         name="view_storage_location"),
    path('add-storage/<int:household_id>',
         mykitchen.views.add_storage_location,
         name="add_storage_location"),
    path('update-storage/<int:household_id>/<int:storage_id>',
         mykitchen.views.update_storage_location,
         name="update_storage_location"),
    path('delete-storage/<int:household_id>/<int:storage_id>',
         mykitchen.views.delete_storage_location,
         name="delete_storage_location"),
    path('storage-content/<int:household_id>/<int:storage_id>',
         mykitchen.views.storage_content_view,
         name="view_storage_content"),
    path('add-food-item/<int:household_id>/<int:storage_id>',
         mykitchen.views.add_food_item,
         name="add_food_item"),
    path('update-food-item/<int:household_id>/<int:storage_id>/<int:food_id>',
         mykitchen.views.edit_food_item,
         name="update_food_item"),
    path('delete-food-item/<int:household_id>/<int:storage_id>/<int:food_id>',
         mykitchen.views.delete_food_item,
         name="delete_food_item")
]

mykitchen/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from products.models import Product
import datetime

# Create your models here.


def get_sentinel_user():
    standby_user = get_user_model().objects.get_or_create(username='admin')[0]
    return standby_user


class Household(models.Model):
    """Class defining Household Object"""
    name = models.CharField(blank=False, max_length=50,
                            help_text='Name to identify your household')
    owner = models.ForeignKey(User,
                              blank=False,
                              on_delete=models.SET(get_sentinel_user))

    def __str__(self):
        return self.name


class Member(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="user")
    household = models.ForeignKey(Household, on_delete=models.CASCADE,
                                  related_name="household")

    def __str__(self):
        return self.user.username


class StorageLocation(models.Model):
    """Location for items in a kitchen. E.g. Cabinet, Fridge"""
    name = models.CharField(blank=False, max_length=50,
                            help_text="Kitchen Fixtures")
    storage_temperature = models.IntegerField(blank=True,
                                              null = True,
                                              help_text="deg Celsius")
    household = models.ForeignKey(Household, on_delete=models.CASCADE)
    edited_by = models.ForeignKey(User, blank=False,
                                  on_delete=models.SET(get_sentinel_user))

    STORAGE_TYPE_CHOICES = (
        ('cabinet', 'Cabinet'),
        ('cupboard', 'Cupboard'),
        ('counter-top', 'Counter'),
        ('fridge', 'Refridgerator'),
        ('freezer', 'Freezer'),
        ('pantry', 'Pantry'),
        ('others', 'Others')
    )

    storage_type = models.CharField(blank=False, choices=STORAGE_TYPE_CHOICES,
                                    max_length=11, default="cupboard",
                                    help_text="Storage Location Types")

    def __str__(self):
        return self.name


class FoodItem(models.Model):
    """Food Items to be Stored in Location"""
    food = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    location = models.ForeignKey(StorageLocation, on_delete=models.CASCADE)
    quantity = models.IntegerField(blank=False, help_text="number of packages")
    remarks = models.TextField(blank=True, max_length=600)
    expiry_date = models.DateField(
        null=True, blank=True, help_text='Enter date in YYYY-MM-DD format')
    threshold = models.IntegerField(blank=False,
                                    help_text="Number of days before expiry"
                                    " date to notify me")
    edited_by = models.ForeignKey(User, blank=False,
                                  on_delete=models.SET(get_sentinel_user))

    PACKAGES = (
        ('bar', 'Bar'),
        ('bottle', 'Bottle'),
        ('box', 'Box'),
        ('pack', 'Pack'),
        ('roll', 'Roll'),
        ('tin', 'Tin')
    )

    package = models.CharField(blank=False, choices=PACKAGES,
                               max_length=7, default="pack",
                               help_text="Food Packages")

    def __str__(self):
        return f"{self.food} bought by {self.edited_by}"

    def get_food_name(self):
        return self.food.name

    def get_food_image(self):
        return self.food.image

    def get_food_brand(self):
        return self.food.brand

    def get_food_weight(self):
        return self.food.weight_per_pack

    def get_days_duration(self):
        return (self.expiry_date-datetime.date.today()).days

    def get_hit_threshold(self):
        if (self.expiry_date-datetime.date.today()).days <= self.threshold:
            return True
        else:
            return False

    def get_expired(self):
        return (self.expiry_date-datetime.date.today()).days <= 0

mykitchen/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from .forms import (HouseholdForm, MemberFormSet, StorageLocationForm,
                    FoodItemForm)
from .models import Member, Household, StorageLocation, FoodItem
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group, User
import datetime
from django.db.models import Q
from django.http import Http404
from django.core.exceptions import PermissionDenied

# Create your views here.
"""
My Kitchen App Index Page.
Purpose: Landing page to receive store customers and to link them to the app
that manages their kitchen inventory
"""


@login_required
def index(request):
    # get user = request.user,
    user = request.user
    # set belongs to False by default
    belongs = False

    # check if logged in user is household member
    try:
        member = Member.objects.get(user=user)
    except Member.DoesNotExist:
        member = None

    # if owner logs in, check if household exists
    try:
        household = Household.objects.get(owner=user)
    except Household.DoesNotExist:
        household = None

    # if member exists, get household
    if member:
        household = member.household

    # if household exists for request.user, and user matches the
    # username of owner or member, set belongs to True
    if household:
        if user.username == household.owner.username or (
                            user.username == member.user.username):
            belongs = True

    # get all storage that belongs to user's household
    # get all foods in the storages
    try:
        storages = StorageLocation.objects.filter(household=household)
    except StorageLocation.DoesNotExist:
        storages = None

    all_food = FoodItem.objects.filter(location__in=storages)
    store_data = {}
    for store in storages:
        foods = FoodItem.objects.filter(
            location__name__iexact=str(store)).count()
        store_data[store] = foods

    # if household is None, set it to empty string for flash msg
    if household is None:
        household = ""
        messages.info(
            request,
            "Please register the household and link the members."
        )

    return render(request, 'mykitchen/mykitchen_index.template.html', {
        'household': household,
        'all_food': all_food,
        'store_data': store_data,
        'belongs': belongs
    })


"""
My Kitchen App Manage(View) Household Profile Page
Purpose: Page to allow household owners to view the household information
they have registered.
1. Get the household by household id
2. Get the members of the household
3. If household exists, check user is household owner
4. If true, renders template
5. If false, raise Permission Denied
6. Raise 404 if Household does not exists
"""


@login_required
@permission_required(['mykitchen.view_household',
                      'mykitchen.view_member'])
def view_household(request, household_id):
    user = request.user
    household = get_object_or_404(Household, pk=household_id)
    members = Member.objects.filter(household=household)
    if household:
        if user.username == household.owner.username:
            return render(request,
                          'mykitchen/view_household.template.html', {
                           'household': household,
                           'members': members
                          })
        else:
            raise PermissionDenied
    else:
        raise Http404


"""
My Kitchen App Manage Register Household Profile Page
Purpose: Page to allow household owners to register household information
1. Filter the form queryset to show only users that do not belong to
   any households, are not owners, and not admin
2. Serve the form on GET request
3. On request == POST, add owners to group = "owner_group" for permissions
4. If form is valid, save the household name to database.
5. If member formset is valid,
6. Check if user does not exists or already is a member of another household
7. Flash error if there is an error
8. Otherwise, add user to group = "member_group", save the members information
9. Flash success message and render template
"""


@login_required
def register_household(request):
    all_existing_members = Member.objects.all()
    # get the id of the household owners
    owners_pk = [h.owner.id for h in Household.objects.all()]
    # list the ids of all household members
    all_members_pk = [am.user.id for am in all_existing_members]
    # generate the list of users to be excluded (household owners and
    # other existing household members) including admin (id=1) and
    # request.user
    to_be_excluded = [1, *owners_pk, *all_members_pk, request.user.id]
    house_form = HouseholdForm()
    member_formset = MemberFormSet(prefix="member")
    # overwrite the queryset in each member formset
    for formsets in member_formset.forms:
        formsets.fields['user'].queryset = (
            formsets.fields['user'].queryset.exclude(Q(id__in=to_be_excluded)))
    if request.method == 'POST':
        house_form = HouseholdForm(request.POST)
        member_formset = MemberFormSet(request.POST, prefix="member")
        # if the form is validated
        if house_form.is_valid():
            house_form_instance = house_form.save(commit=False)
            house_form_instance.owner = request.user
            owner_group = Group.objects.get(name='owner_group')
            owner_group.user_set.add(house_form_instance.owner)
            if member_formset.is_valid():
                members_form_instance = member_formset.save(commit=False)
                house_form_instance.save()
                for form_instance in members_form_instance:
                    member_group = Group.objects.get(name='member_group')
                    try:
                        user = User.objects.get(username=form_instance)
                    except User.DoesNotExist:
                        user = None
                    # check if user belongs to another household
                    try:
                        member = Member.objects.get(user=user)
                    except Member.DoesNotExist:
                        member = None

                    if member is not None or user is None:
                        messages.error(request,
                                       f"{user}already belongs to another"
                                       " household or No such User.")
                        return redirect(reverse(index))
                    else:
                        # assign user to group
                        member_group.user_set.add(user)
                        # save form data
                        form_instance.household = house_form_instance
                        form_instance.save()
                messages.success(
                    request,
                    f"Your household profile {house_form_instance.name}"
                    f" has been created on"
                    f" {datetime.datetime.today().strftime('%b %d, %Y, %H:%M:%S')}")
                return redirect(reverse(index))
    return render(request, 'mykitchen/register_household.template.html', {
        'house_form': house_form,
        'member_form': member_formset
    })


"""
My Kitchen App Edit Household Profile Page
Purpose: Page to allow household owners to edit household information
1. Filter the form queryset to show only users that do not belong to
   other households, are not owners, and not admin
2. Serve the form on GET request
3. On request == POST, get the list of members
4. Get the list of added members and list of removed members
5. Check for membership in list of added members
6. If any in list is has no membership, added the members to member_group
7. Remove the removed members from member_group
8. Save the data into the database
9. Flash success message and render template
"""


@login_required
@permission_required(['mykitchen.view_household',
                      'mykitchen.add_household',
                      'mykitchen.change_household',
                      'mykitchen.view_member',
                      'mykitchen.add_member',
                      'mykitchen.change_member'])
def edit_household(request, household_id):
    user = request.user
    household_to_update = get_object_or_404(Household, pk=household_id)
    current_members = Member.objects.filter(household=household_to_update)
    if household_to_update:
        if user.username == household_to_update.owner.username:
            # get the id of the household owners
            owners_pk = [h.owner.id for h in Household.objects.all()]
            # list the current household members
            household_members = [x.user for x in current_members]
            # get members of other households
            other_members = Member.objects.exclude(user__in=household_members)
            # list the id of the members of other households
            other_members_pk = [om.user.id for om in other_members]
            # generate the list of users to be excluded (household owners and
            # other existing household members) including admin (id=1)
            to_be_excluded = [1, *owners_pk, *other_members_pk]
            # create the form and populate with object instance
            edit_house_form = HouseholdForm(instance=household_to_update)
            edit_member_form = MemberFormSet(instance=household_to_update,
                                             prefix="member")
            # overwrite the queryset in each member formset
            for formsets in edit_member_form.forms:
                formsets.fields['user'].queryset = (
                    formsets.fields['user'].queryset.exclude(
                        Q(id__in=to_be_excluded)))
            if request.method == 'POST':
                edit_house_form = HouseholdForm(request.POST,

mykitchen/templates/mykitchen/input_food.template.html
{% extends 'base_kitchen.template.html' %}
{%load crispy_forms_tags %}
{%load static%}


{%block title%} Input Food Items Form {%endblock%}

{%block nav%}
{% if request.user == household.owner %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'view_household' household_id=household.id %}">View Home Profile</a>
</li>
{% endif %}
{% if household %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'view_storage_location' household_id=household.id %}">Storage</a>
</li>
{%endif %}
{%endblock%}

{%block content%}
<h3>MyKitchen Input Food Form</h3>
<form method="POST">
	{% csrf_token %}
	{{ form|crispy }}
	<input type="submit" role="button" class="btn btn-general" value="Submit"/>
    </form>
	{% endblock %}

mykitchen/templates/mykitchen/input_storage.template.html
{% extends 'base_kitchen.template.html' %}
{%load crispy_forms_tags %}
{%load static%}


{%block title%} Create Kitchen Storage Form {%endblock%}

{%block nav%}
{% if request.user == household.owner %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'view_household' household_id=household.id %}">View Home Profile</a>
</li>
{% endif %}
{% if household %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'view_storage_location' household_id=household.id %}">Storage</a>
</li>
{%endif %}
{%endblock%}

{%block content%}
<h3>MyKitchen Input Storage Form</h3>
<form method="POST">
	{% csrf_token %}
	{{ form|crispy }}
	<input type="submit" role="button" class="btn btn-general" value="Submit"/>
    </form>
	{% endblock %}

mykitchen/templates/mykitchen/register_household.template.html
{% extends 'base_kitchen.template.html' %}
{%load crispy_forms_tags %}
{%load static%}


{%block title%} Register Household Form {%endblock%}
{%block content%}
    <h3>My Household Form</h3>
    <form method="POST">
    {% csrf_token %}
    {{ house_form|crispy }}
    {{ member_form.management_form|crispy }}
    {% for form in member_form %}
    <div class="form-inline {{ form.prefix }}">
        {{ form|crispy }}
        {{ form.id}}
    </div>
    {% endfor %}
    <input type="submit" role="button" class="btn btn-general" value="Submit"/>
    </form>    
  {% endblock %}

mykitchen/templates/mykitchen/update_food.template.html
{% extends 'base_kitchen.template.html' %}
{%load crispy_forms_tags %}
{%load static%}

{%block title%} Update Food Items Form {%endblock%}

{%block nav%}
    {% if request.user == household.owner %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_household' household_id=household.id %}">View Home Profile</a>
    </li>
    {% endif %}
    {% if household %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_storage_location' household_id=household.id %}">Storage</a>
      </li>
    {%endif %}
{%endblock%}

{%block content%}
    <h3>MyKitchen Update Food Form</h3>
    <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" role="button" class="btn btn-general" value="Submit"/>
    </form>    
{% endblock %}

mykitchen/templates/mykitchen/update_household.template.html
{% extends 'base_kitchen.template.html' %}
{%load crispy_forms_tags %}
{%load static%}

{%block title%} Update Household Form {%endblock%}

{%block nav%}
    {% if request.user == household.owner %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_household' household_id=household.id %}">View Home Profile</a>
    </li>
    {% endif %}
    {% if household %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_storage_location' household_id=household.id %}">Storage</a>
      </li>
    {%endif %}
{%endblock%}

{%block content%}
    <h3>My Household Form</h3>
    <form method="POST">
    {% csrf_token %}
    {{ house_form|crispy }}
    {{ member_form.management_form|crispy }}
    <p>Please check delete to delete previous members by position.</p>
    {% for form in member_form %}
    <div class="form-inline {{ form.prefix }}">
        {{ form|crispy }}
        {{ form.id}}
    </div>
    {% endfor %}
    <input type="submit" role="button" class="btn btn-general" value="Submit"/>
    </form>    
  {% endblock %}

mykitchen/templates/mykitchen/update_storage.template.html
{% extends 'base_kitchen.template.html' %}
{%load crispy_forms_tags %}
{%load static%}


{%block title%} Update Kitchen Storage Details Form {%endblock%}

{%block nav%}
    {% if request.user == household.owner %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_household' household_id=household.id %}">View Home Profile</a>
    </li>
    {% endif %}
    {% if household %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'view_storage_location' household_id=household.id %}">Storage</a>
      </li>
    {%endif %}
{%endblock%}

{%block content%}
    <h3>MyKitchen Update Storage Details Form</h3>
    <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" role="button" class="btn btn-general" value="Submit"/>
    </form>    
{% endblock %}

mykitchen/templates/mykitchen/view_storage.template.html
{% extends 'base_kitchen.template.html' %}
{%load static %}

{%block title%}
MyKitchen Storage Section
{%endblock%}


{%block content%}
<h3>My Kitchen Storage Locations</h3>
{% if perms.mykitchen.add_storagelocation %}
	<a class="btn btn-secondary btn-lg floating-btn" href="{% url 'add_storage_location' household_id=household.id %}" role="button"
		data-toggle="tooltip" data-placement="bottom" title="Add storage">+</a>
{% endif %}

{%for store in storage%}
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col col-md-1 align-self-center">
      <img src="{% static '/image/' %}{{store.storage_type}}.png" class="card-img" alt="...">
    </div>
    <div class="col col-md-6">
      <div class="card-body">
        <h5 class="card-title">{{store.name}}</h5>
        <p class="card-text">Storage Temperature: {{store.storage_temperature}} deg C</p>
        <p class="card-text"><small class="text-muted">Last added by:{{store.edited_by}}</small></p>
      </div>
    </div>
    <div class="col col-md-5 align-self-center">
    <a href="{% url 'update_storage_location' household_id=household.id storage_id=store.id%}" class="btn btn-primary" role="button">Edit</a>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal-{{store.id}}">
    Delete
    </button>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal-{{store.id}}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Do you want to delete this Storage Location?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Deleting a storage will remove it permanently. This action cannot be undone.</p>
      </div>
      <div class="modal-footer">
      <form action="{% url 'delete_storage_location' household_id=household.id storage_id=store.id%}" method="POST">
        {% csrf_token %}
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-danger" value="CONFIRM"/>
        </form>
      </div>
    </div>
  </div>
</div>
{%endfor%}
{%endblock%}

mykitchen/templates/mykitchen/view_storage_content.template.html
{% extends 'base_kitchen.template.html' %}
{%load static %}

{%block title%}
MyKitchen Storage Content
{%endblock%}

{%block nav%}
{% if not household %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'register_household' %}">Register Home Profile</a>
</li>
{% endif %}
{% if request.user == household.owner %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'view_household' household_id=household.id %}">View Home Profile</a>
</li>
{% endif %}
{% if household %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'view_storage_location' household_id=household.id %}">Storage</a>
</li>
{%endif %}
{%endblock%}

{%block content%}
<h3>All Food Item in {{storage.name}}</h3>

{% if perms.mykitchen.add_fooditem%}
<a class="btn btn-secondary btn-lg floating-btn"
	href="{% url 'add_food_item' household_id=household.id storage_id=storage.id %}" role="button" data-toggle="tooltip"
	data-placement="bottom" title="Add food item">+</a>
{% endif %}

{%for food in stored_food%}
<div class="card mb-3">
	<div class="row no-gutters">
		<div class="col mobile-content">
			<div class="col col-md-2 align-self-center">
				<img src="{{food.food.image}}" class="card-img" alt="...">
    </div>
				<div class="col col-md-6">
					<div class="card-body">
						<h5 class="card-title">{{food.food.name}}</h5>
						<p class="card-text">Notes: {{food.remarks}}</p>
						<p class="card-text">Food Expires On: {{food.expiry_date}}</p>
						<p class="card-text">Expiry Notification Threshold: {{food.threshold}} days</p>
						<p class="card-text">Packaging: {{food.package}}</p>
						<p class="card-text"><small class="text-muted">Last edited by: {{food.edited_by}}</small></p>
					</div>
				</div>
				<div class="col col-md-4 align-self-center">
					<a href="{% url 'update_food_item' household_id=household.id storage_id=storage.id food_id=food.id %}"
						class="btn btn-primary" role="button"><i class="fas fa-pen-alt"></i>Edit</a>
					<!-- Button trigger modal -->
					<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal-{{food.id}}">
    <i class="fas fa-trash-alt"></i>Delete
    </button>
					<div class="mt-3">
						<a href="{% url 'add_to_cart' product_id=food.food.id %}" class="link">
							<span class="d-inline-flex">
                <img src="{% static '/image/shopping-cart.svg' %}"/>
					<p class="card-text"><small class="text-muted">Add to Cart</small></p>
            </span>
						</a>
					</div>
				</div>
			</div>
		</div>
		<!--end row-->
	</div>

	<!-- Modal -->
	<div class="modal fade" id="deleteModal-{{food.id}}" tabindex="-1" aria-labelledby="deleteModalLabel"
		aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="deleteModalLabel">Do you want to delete this Food Item from
						{{food.location.name}}?</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
				</div>
				<div class="modal-body">
					<p>Deleting a food item will remove it permanently. This action cannot be undone.</p>
				</div>
				<div class="modal-footer">
					<form
						action="{% url 'delete_food_item' household_id=household.id storage_id=storage.id food_id=food.id %}"
						method="POST">
						{% csrf_token %}
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<input type="submit" class="btn btn-danger" value="CONFIRM"/>
        </form>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
	{% endblock %}

mykitchen/templates/mykitchen/view_storage_location.template.html
{% extends 'base_kitchen.template.html' %}
{%load static %}

{%block title%}
MyKitchen Storage Section
{%endblock%}

{%block nav%}
{% if not household %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'register_household' %}">Register Home Profile</a>
</li>
{% endif %}
{% if request.user == household.owner %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'view_household' household_id=household.id %}">View Home Profile</a>
</li>
{% endif %}
{% if household %}
<li class="nav-item">
	<a class="nav-link" href="{% url 'view_storage_location' household_id=household.id %}">Storage</a>
</li>
{%endif %}
{%endblock%}

{%block content%}
<h3>My Kitchen Storage Locations</h3>
{% if perms.mykitchen.add_storagelocation %}
<a class="btn btn-secondary btn-lg floating-btn" href="{% url 'add_storage_location' household_id=household.id %}"
	role="button" data-toggle="tooltip" data-placement="bottom" title="Add storage">+</a>
{% endif %}

{%for store in storage%}
<div class="card mb-3">
	<div class="row no-gutters">
		<div class="col mobile-content">
			<div class="col col-md-2 align-self-center">
				<a href="{% url 'view_storage_content' household_id=household.id storage_id=store.id %}" class="link"
					data-toggle="tooltip" data-placement="bottom" title="Look Inside">
					<img src="{% static '/image/' %}{{store.storage_type}}.png" class="img-fluid img-storage" alt="storage-type image">
      </a>
			</div>
			<div class="col col-md-6">
				<div class="card-body">
					<h5 class="card-title">{{store.name}}</h5>
					<p class="card-text">Storage Temperature: {{store.storage_temperature}} deg C</p>
					<p class="card-text"><small class="text-muted">Last edited by: {{store.edited_by}}</small></p>
				</div>
			</div>
			<div class="col col-md-4 align-self-center mb-3">
				<a href="{% url 'update_storage_location' household_id=household.id storage_id=store.id%}"
					class="btn btn-primary" role="button"><i class="fas fa-pen-alt"></i>Edit</a>
				<!-- Button trigger modal -->
				<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal-{{store.id}}">
     <i class="fas fa-trash-alt"></i>Delete
    </button>
			</div>
		</div>
	</div>
	<!--end row-->
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal-{{store.id}}" tabindex="-1" aria-labelledby="deleteModalLabel"
	aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="deleteModalLabel">Do you want to delete this Storage Location?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
			</div>
			<div class="modal-body">
				<p>Deleting a storage will remove it permanently. This action cannot be undone.</p>
			</div>
			<div class="modal-footer">
				<form action="{% url 'delete_storage_location' household_id=household.id storage_id=store.id%}"
					method="POST">
					{% csrf_token %}
					<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					<input type="submit" class="btn btn-danger" value="CONFIRM"/>
        </form>
			</div>
		</div>
	</div>
</div>
{%endfor%}
{%endblock%}